dataset:
  dir:
    # Change to match absolute path for your machine
    train: "/home/dmanwill/MMIR/Git/eecs556_MMIR/DeepReg/data/paired_mr_us_brain/train"
    valid: "/home/dmanwill/MMIR/Git/eecs556_MMIR/DeepReg/data/paired_mr_us_brain/test"
    test: "/home/dmanwill/MMIR/Git/eecs556_MMIR/DeepReg/data/paired_mr_us_brain/test"
  format: "nifti"
  type: "paired" # paired / unpaired / grouped
  labeled: true
  sample_label: "all"
  # Downsampling by a factor of 4
  moving_image_shape: [64, 64, 72]
  fixed_image_shape: [64, 64, 72]
train:
  method: "ddf" # the registration method, value should be ddf / dvf / conditional
  backbone:
    name: "unet" # value should be local / global / unet
    num_channel_initial: 16 # number of initial channel in local net, controls the size of the network
    depth: 4
    pooling: false
    concat_skip: true
  loss:
    image:
      name: "gmi"
      weight: 0.5
      num_bins: 23
      sigma_ratio: 0.5
    label:
      weight: 1.0
      name: "dice"
      scales: [0, 1, 2, 4, 8, 16]
    regularization:
      weight: 0.5
      name: "bending"
  preprocess:
    data_augmentation:
      name: "affine"
    batch_size: 8
    shuffle_buffer_num_batch: 1
  optimizer:
    name: "Adam"
    learning_rate: 5.0e-4
  epochs: 500
  save_period: 50